"""Crear tabla de notificaciones

Revision ID: crear_tabla_notificaciones
Revises: agregar_video_posts
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'crear_tabla_notificaciones'
down_revision = 'agregar_video_posts'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('intentos', sa.Integer(), nullable=True),
    sa.Column('max_intentos', sa.Integer(), nullable=True),
    sa.Column('datos_adicionales', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificaciones_estado'), 'notificaciones', ['estado'], unique=False)
    op.create_index(op.f('ix_notificaciones_fecha_creacion'), 'notificaciones', ['fecha_creacion'], unique=False)
    op.create_index(op.f('ix_notificaciones_tipo'), 'notificaciones', ['tipo'], unique=False)
    op.create_index(op.f('ix_notificaciones_usuario_id'), 'notificaciones', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notificaciones_usuario_id'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_tipo'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_fecha_creacion'), table_name='notificaciones')
    op.drop_index(op.f('ix_notificaciones_estado'), table_name='notificaciones')
    op.drop_table('notificaciones')
    # ### end Alembic commands ###
